### ISSUE TITLE
No icons for already installed games

### ISSUE THREAD

**Issue by berarma** [sharkwouter/minigalaxy#110]
After working around issue #109 my already installed games were found but the icon disappeared. Before they were found installed they had their icon.

I'm using the deb package version 0.9.3 in Debian 10.

**Comment by sharkwouter** [comment]
That's odd, it should be downloading them. Did you start Minigalaxy with a working internet connection? How fast is your connection? Not that I expect that to be the reason, but I want to make sure to rule it out.

**Comment by berarma** [comment]
It's weird because all icons were showing before I configured the game path and minigalaxy found the already installed games. When it found them it stopped showing their icons.

**Comment by sharkwouter** [comment]
I was able to reproduce this on the latest code in git. I'll look into it.

**Comment by sharkwouter** [comment]
This also affects showing the store page or not. I'm not creating a new issues for this, since the fix will be the same.

**Comment by sharkwouter** [comment]
This should be fixed in master now.

**Comment by wnhre2ur8cxx8** [comment]
This is still an issue. just installed 1.0 via AUR and the installed games show up but they are the only ones without icon.

**Comment by sharkwouter** [comment]
Yeah, it isn't in the version in the AUR yet. It will be in the next release.
