### ISSUE TITLE
Uninstalling a wine game doesn't remove menu items

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#117]
Currently when you uninstall a wine game, it just deletes the directory in which the games is located. This means items in the user's operating system menu which were added by the GOG installer will remain.

**Comment by sharkwouter** [comment]
This one is a bit harder to fix than I initially thought. The shortcuts are installed in ``~/.local/share/applications/wine/Programs/GOG.com/``. The issue is that the name of the directory is not decided by Minigalaxy, but by the installer.

**Comment by makson96** [comment]
Can you post a content of such a file? My idea is that we can read all files content in this directory (~/.local/share/applications/wine/Programs/GOG.com/) and if there is reference in such a file to game install directory. Remove that file to.

**Comment by sharkwouter** [comment]
I think the shortcuts shouldn't be created at all to be honest. I'm sure we can make sure of that using some command like what #289 tries to do.

**Comment by makson96** [comment]
This one should be fixed together with #313

**Comment by sharkwouter** [comment]
This will be considered fixed, which Innoextract is a mandory dependency.

**Comment by sharkwouter** [comment]
This is actually fixed in the master branch now. The next release will have a fix for this.

**Comment by sharkwouter** [comment]
What I mean to say is, that we won't care about this anymore, because we no longer create these shortcut files.

**Comment by GB609** [comment]
@sharkwouter 
It is mostly fixed for regular installations.
There is one situation where shortcuts from wine will still appear:
Right now, only the code that runs the installation temporarily disables the winemenubuilder. And prevents shortcuts while the installation runs.

But i've also seen unity games that start some other dependency installation when the game is started the first time. However, the winemenebuilder is not disabled then, because the code does not set WINEDLLOVERRIDE currently when starting a game (users might have configured other overrides to get the game to run correctly and we'd overwrite those when setting the env).
I did experiment with setting a registry key to disable the menubuilder, but wasnt successful up to now.

**Comment by sharkwouter** [comment]
Interesting, lets consider that edge cases for now and wait for specific bug reports.
