### ISSUE TITLE
download option: gog's filename

### ISSUE THREAD

**Issue by arrowgent** [sharkwouter/minigalaxy#169]
in addition to adding the option "download" with "install"
#161

it would be nice if the downloaded file was named the same as the file from gog's website
i dont know exactly how minigalaxy pulls the file from gog api

but an example is:

```
/home/$USER/.cache/minigalaxy/download/Thief™ Gold
```
should be
```
/home/$USER/.cache/minigalaxy/download/setup_thief_gold_1.26_nd_(21948).exe
```

similar happens for .sh files for linux versions

keep up the good work.

**Comment by kibun1** [comment]
It seems to be possible to extract the filename using the download link (`api.get_real_download_link(file_info["downlink"])`)
For example, when I download rollercoaster tycoon (and it seems to be the same for other games), the real download link is

> https://content-system.gog.com/products/1207658945/users/USERID/namespaces/website/download?path=%2Fsecure%2Foffline%2Fwhatever%2F9133%2Fsetup_rollercoaster_tycoon_deluxe_1.20.015_%2817822%29.exe&token=TOKEN&access_token=ACCESS_TOKEN

A possible regex to extract the token using `re.search()` would be this: `'%2F(((?!%2F).)*)&token'`
I haven't sufficiently tested this yet, and at first glance changing the target filename of the download seems to be a relatively significant change, but if this is a desirable change then I could work on that.

**Comment by sharkwouter** [comment]
@kibun1 I would say it is desirable that this will be changed, but it is somewhat complex. As we discussed in discord, the solution you mention here solves half the problem. In addition to that change, it would be good to put the installer in a directory with the same name as the installation directory in the installer directory if "keep installers" is enabled. That way, we can still check if the installer is there.

**Comment by sharkwouter** [comment]
This should be fixed inn masterr now. Can you test it @arrowgent?

**Comment by arrowgent** [comment]
> This should be fixed inn masterr now. Can you test it @arrowgent?

heyo.....
ok after reading this and looking at how to do this (also looking at the commits ~ sept 3 ~)

i got the master and launched ./minigalaxy

found the previous testcase: setup_thief_gold_1.26_nd_(21948).exe

appears to be created correctly in:
~/.cache/minigalaxy/download/Thief Gold/


mind you, i am using Ubuntu 18.04 LTS and have minigalaxy manually installed under /opt/minigalaxy
not that this matters for this issue.


everything looks good here

**Comment by arrowgent** [comment]
additional:

this breaks previously downloaded cache files and will re-download the file again with the new folder/filename format
the old file still exists.

**Comment by sharkwouter** [comment]
Great, then this means this will be fixed in the next release.
