### ISSUE TITLE
The Elder Scrolls Arena fails to launch with Wine errors

### ISSUE THREAD

**Issue by 4Vertikal4** [sharkwouter/minigalaxy#672]
**Minigalaxy Information**
Package ID: io.github.sharkwouter.Minigalaxy
Version: 1.3.2
Installation method: Flatpak (system-wide from Flathub)
Flatpak version: 1.16.0

**System Information**
Linux Distribution: Fedora 41
Kernel: 6.13.5-200.fc41.x86_64
Desktop environment: GNOME
GPU: GeForce RTX 3060 Ti
GPU driver:
glxinfo | grep "OpenGL renderer"
OpenGL renderer string: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2

**Steps to reproduce:**
1. Install The Elder Scrolls Arena from GOG through Minigalaxy
2. Click the "Play" button
3. Game fails with error: "Nie można uruchomić The Elder Scrolls: Arena"

**Error details:**
- Wine debugger error: "Can't attach process 01bc: error 5"
- Multiple HID handler errors (0084:fixme:hid:handle_IRP_MN_QUERY_ID)
- Multiple Xinerama errors failing to get fullscreen monitors
- Wine unhandled page fault on read access to 047D00DF
- System reports "tracking was unable to attach to the process to debug it"

Screenshots:

![Image](https://github.com/user-attachments/assets/1d9ec778-d322-40d5-b04e-00ec1cc0506e)

![Image](https://github.com/user-attachments/assets/72047621-921d-49b9-9798-a07d5a363f8c)

**Notes:**
- The game launches in Heroic Games Launcher but has no sound
- Reference issue: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/4409

**Comment by GB609** [comment]
This appears to be an issue with the flatpak and your display configuration and/or drivers. But i can't exactly say what the root cause is. 
What are you using, wayland or x?

**Comment by 4Vertikal4** [comment]
> This appears to be an issue with the flatpak and your display configuration and/or drivers. But i can't exactly say what the root cause is. What are you using, wayland or x?

Thanks for your reply, but I don't think this is related to my display configuration or Flatpak in general. I can successfully run The Elder Scrolls Arena on Heroic Games Launcher (version 2.16.1), which is also installed via Flatpak. (see the **Notes** in my post above).

In Heroic, the game launches and displays correctly - the only issue is missing sound, which is a known problem documented on ProtonDB with available workarounds.

The fact that the same game runs graphically fine in one Flatpak application but fails completely in another suggests the issue is specific to Minigalaxy's implementation rather than a system-wide problem with Flatpak or Wayland.

For reference, I am using Wayland (standard on Fedora), but since the game works in Heroic, I don't believe the display server is the root cause.

Could there be something specific in how Minigalaxy configures Wine for older DOS games compared to Heroic's approach?

**Comment by GB609** [comment]
Let me rephrase. I didn't mean flatpak in general, but the flatpak package build of minigalaxy. This might be missing something.

**Comment by 4Vertikal4** [comment]
Hi GB609, 

I wanted to follow up and share what I discovered about the issue. After comparing both launchers, I found that:

-     Minigalaxy is using standard Wine 9.0 in its Flatpak
-     Heroic Games Launcher is using Wine-GE-Proton8-26

This version difference seems to be key - the GE-Proton version includes additional compatibility patches that appear to handle DOS games like Arena differently. 

I've managed to get Arena working with sound in Heroic, which helps me enjoy the game for now. However, I'd be happy to help contribute to Minigalaxy in any way I can. If there are specific configurations or tests you'd like me to try with Arena in Minigalaxy, I'm more than willing to provide logs, test specific Wine versions, or help troubleshoot the compatibility issues. 

Let me know if there's any information I can provide that would help improve DOS game compatibility in the project! Thanks for your help and dedication to the Minigalaxy project!

**Comment by GB609** [comment]
Thanks for the response. The biggest issue we have with a lot of windows games is finding the command line and executable for which we normally first try to parse the goggame*.info file.
But that wasn't your issue so i didnt ask for that.

If you want to help, we have a lot of issues flagged with the tag "wine install". They are from outdated versions of minigalaxy which could require a retest because there have been a lot of fixes in that area in versions 1.3.1 and 1.3.2. So if you own any of the games mentioned, feel free to test and report if the install succeeds. And also, if minigalaxy manages to find the correct executable.

The games still might not launch however, because minigalaxy currently does not apply patches to wineprefixes, although this might come in the future. But this is a separate issue.
However, when winetricks is installed, it is possible to apply patches manually. Doesn't work with the current flatpak version, as winetricks is missing there.
In theory, it is possible to use another wine variant like ge-proton or umu via preferences. I'm not sure if that is possible with the flatpak version.

**Comment by 4Vertikal4** [comment]
> Thanks for the response. The biggest issue we have with a lot of windows games is finding the command line and executable for which we normally first try to parse the goggame*.info file. But that wasn't your issue so i didnt ask for that.
> 
> If you want to help, we have a lot of issues flagged with the tag "wine install". They are from outdated versions of minigalaxy which could require a retest because there have been a lot of fixes in that area in versions 1.3.1 and 1.3.2. So if you own any of the games mentioned, feel free to test and report if the install succeeds. And also, if minigalaxy manages to find the correct executable.
> 
> The games still might not launch however, because minigalaxy currently does not apply patches to wineprefixes, although this might come in the future. But this is a separate issue. However, when winetricks is installed, it is possible to apply patches manually. For this, there is a 'winetricks' button in the properties window of installed games. This does not yet work with the flatpak version, because it is missing the ui framework zenity used by winetricks. However, it should be possible to use winetricks from the command line. In theory, it is already possible to use another wine variant like ge-proton or umu via preferences. Some binaries might need additional env args, however. I'm not sure if it is possible with the flatpak version to pick something not included in it, so this option might not be helpful there.

@GB609 Thank you for your suggestions on trying winetricks and alternate Wine versions. I've created a [new issue ](https://github.com/flatpak/flatpak/issues/6160)in the Flatpak repository to get guidance on the broader question of Wine integration with Flatpak applications. Since this seems to be a challenge related to Flatpak sandboxing rather than Minigalaxy specifically, I'm hoping to get some best practices from the Flatpak developers.

**Comment by GB609** [comment]
@4Vertikal4 
I tested the flatpak build myself with the game 'Star Trek Voyager: Elite Force'.
I also got a lot of the 'Failed to get xinerama fullscreen monitor indices' messages, but the game still started. Thus, i think this message is annoying, but _not_ fatal to the application.
I tried a bit of googling about that xinerama issues. Haven't really found many reliable hints, but one person on reddit mentioned that it might be related to the wayland compositor in use: https://www.reddit.com/r/winehq/comments/17uymyb/xinerama_winehq_error_failed_to_get_xinerama/
I'm not sure how reliable that info is or whether that works for you at all. I'm not even using wayland and still get that error, so it might also be an error with the minigalaxy flatpak package itself instead.

The issue that caused your game to fail is more likely the last line with the 'unhandled page fault'.

I've also prepared a pull request at the flathub repository of minigalaxy to upgrade the wine version of the minigalaxy package, also including zenity which is required to use the winetricks ui started from within minigalaxy.
Now it's up to the maintainers of https://github.com/flathub/io.github.sharkwouter.Minigalaxy to accept and merge.

**Comment by 4Vertikal4** [comment]
> [@4Vertikal4](https://github.com/4Vertikal4) I tested the flatpak build myself with the game 'Star Trek Voyager: Elite Force'. I also got a lot of the 'Failed to get xinerama fullscreen monitor indices' messages, but the game still started. Thus, i think this message is annoying, but _not_ fatal to the application. I tried a bit of googling about that xinerama issues. Haven't really found many reliable hints, but one person on reddit mentioned that it might be related to the compositor 'Compton': https://www.reddit.com/r/winehq/comments/17uymyb/xinerama_winehq_error_failed_to_get_xinerama/ I'm not sure how reliable that info is or whether that applies to you at all.
> 
> The issue that caused your game to fail is more likely the last line with the 'unhandled page fault'. The only option we can try to fix this would be upgrading the outdated wine version in the flatpak.
> 
> I've prepared a pull request at the flathub repository of minigalaxy to do so. This also includes zenity which is required to use the winetricks ui started from within minigalaxy. Now it's up to the maintainers of https://github.com/flathub/io.github.sharkwouter.Minigalaxy to accept and merge.

Thank you so much for investigating this issue and for the detailed update! This sounds like exactly what's needed to resolve  issue I was facing. I'll watch the Flathub repository for your pull request to be merged.

**Comment by sharkwouter** [comment]
I've merged the change in the Minigalaxy flatpak package, so this is probably fixed now. @4Vertikal4 could you check?

**Comment by 4Vertikal4** [comment]
@sharkwouter Thank you for merging the changes! I've updated my system with sudo dnf update and tried running the game again, but I'm still experiencing issues. I'm now seeing two sequential error messages:

First, a Wine Debugger error appears: "Can't attach process 010c: error 5" (as shown in the first screenshot)

![Image](https://github.com/user-attachments/assets/439c7858-7cc6-4678-957b-d234f94c0fb5)

After dismissing that dialog, I get a second error with the unhandled page fault message (as shown in the second screenshot)

![Image](https://github.com/user-attachments/assets/54b75b98-6003-4ba7-b8f8-d978a81ea79c)

The detailed error when trying to launch "The Elder Scrolls: Arena" shows:
```

007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
[Multiple similar HID handler errors]
SYSTEM_PERFORMANCE_INFORMATION
0110:err:x11drv:xinerama_get_fullscreen_monitors Failed to get xinerama fullscreen monitor indices.
[Multiple similar Xinerama errors]
0110:err:seh:raise_exception Unhandled page fault on read access to 047D00DE at address 2BF4EBD (thread 0110), starting debugger...
```

The unhandled page fault is still occurring, but at a slightly different memory address (047D00DE instead of 047D00DF in my original error). So it seems the Wine version update hasn't fully addressed the underlying issue with this particular game.

Would you like me to collect any additional debugging information? Perhaps there's another component that needs updating or a specific configuration needed for The Elder Scrolls: Arena?

**Comment by 4Vertikal4** [comment]
Good to know GB609!

I didn't realize that DNF doesn't update Flatpaks. I've now run sudo flatpak update and all the components were successfully updated:

```
vertikal@rabbit-hole:~$ sudo flatpak update
[sudo] hasło użytkownika vertikal: 
Wyszukiwanie aktualizacji…

Informacja: program com.riverbankcomputing.PyQt.BaseApp, gałąź 5.15-23.08 jest niewspierany z powodu:
   Branch 5.15-23.08 of the PyQt base application is no longer supported. Please use 5.15-24.08 instead.


        Identyfikator                                    Gałąź               Dz        Repozytorium        Pobieranie
 1. [✓] io.github.sharkwouter.Minigalaxy.Locale          stable              u         flathub             16,2 kB / 6,9 MB
 2. [✓] org.freedesktop.Platform.ffmpeg-full             24.08               i         flathub             12,0 MB / 12,2 MB
 3. [✓] org.freedesktop.Platform.ffmpeg_full.i386        24.08               i         flathub             12,2 MB / 12,4 MB
 4. [✓] org.winehq.Wine.gecko                            stable-24.08        i         flathub              3,8 kB / 108,6 MB
 5. [✓] org.winehq.Wine.mono                             stable-24.08        i         flathub             45,1 MB / 83,3 MB
 6. [✓] io.github.sharkwouter.Minigalaxy                 stable              u         flathub             85,4 MB / 228,4 MB

Aktualizowanie 6/6… ████████████████████ 100%  21,3 MB/s  00:00
Note that '/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
        Identyfikator                                    Gałąź               Dz        Repozytorium        Pobieranie
 1. [✓] io.github.sharkwouter.Minigalaxy.Locale          stable              u         flathub             16,2 kB / 6,9 MB
 2. [✓] org.freedesktop.Platform.ffmpeg-full             24.08               i         flathub             12,0 MB / 12,2 MB
 3. [✓] org.freedesktop.Platform.ffmpeg_full.i386        24.08               i         flathub             12,2 MB / 12,4 MB
 4. [✓] org.winehq.Wine.gecko                            stable-24.08        i         flathub              3,8 kB / 108,6 MB
 5. [✓] org.winehq.Wine.mono                             stable-24.08        i         flathub             45,1 MB / 83,3 MB
 6. [✓] io.github.sharkwouter.Minigalaxy                 stable              u         flathub             85,4 MB / 228,4 MB

Ukończono zmiany.
vertikal@rabbit-hole:~$ 
```

However, I'm still experiencing errors when trying to run The Elder Scrolls: Arena. The errors are slightly different now:

First, I get the Wine Debugger error "Can't attach process 0120: error 5" (see first screenshot)

![Image](https://github.com/user-attachments/assets/933c0ab1-727c-4d01-8c64-a0a8feff5390)

And after dismissing that dialog, I get the unhandled page fault error (see second screenshot):

![Image](https://github.com/user-attachments/assets/1ffdad25-3861-4ecd-a609-376b204137ec)

```
00b8:err:setupapi:do_file_copyW Unsupported style(s) 0x10
0124:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
SYSTEM_PERFORMANCE_INFORMATION
wine: Unhandled page fault on read access to 046E001E at address 7BF96AD1 (thread 0124), starting debugger...
```

The page fault address is different than before (now 046E001E instead of 047D00DE), but it's still causing the same crash. Any further suggestions on how to troubleshoot this?

**Comment by GB609** [comment]
Yesterday i got the feedbck that my flatpak update might have been incomplete.
So i first have to update it a second time. Maybe this helps. But this will take a bit of time until ready.

But we could also be looking at the wrong error altogether.
Would you please start minigalaxy with `flatpak --env=MG_DEBUG=1 run io.github.sharkwouter.Minigalaxy > error.log` and then try to launch the game again? This will create detailed logging and also include everything that happens when starting the game. Maybe the root cause is actually something else.

**Comment by 4Vertikal4** [comment]
I ran the additional flatpak update as you suggested, but only one package was updated this time:

```
vertikal@rabbit-hole:~$ sudo flatpak update
[...]
1. [✓] org.freedesktop.Platform.openh264            2.5.1            i             flathub                913,7 kB / 971,4 kB
```

I then captured the debug log as requested:

`flatpak --env=MG_DEBUG=1 run io.github.sharkwouter.Minigalaxy > error.log`

I checked for tokens in the log: grep -i "token=" error.log (also tried with Token and TOKEN) and there weren't any, so the log is safe to share.

Unfortunately, I'm still experiencing the same type of error when trying to launch The Elder Scrolls: Arena. From the log, you can see the launch command being used:

`
Launch command for The Elder Scrolls: Arena: env WINEPREFIX=/home/vertikal/GOG Games/The Elder Scrolls Arena/prefix wine start /b /wait /d c:\game\DOSBOX c:\game\DOSBOX\dosbox.exe -conf ..\dosbox_arena.conf -conf ..\dosbox_arena_single.conf -noconsole -c exit`

And then it fails with:

```
Cause of error: 012c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
wine: Unhandled page fault on read access to 046E001E at address 7BF96AD1 (thread 012c), starting debugger...
```

The error is still a page fault, but at a slightly different memory address than before. It seems the updated Wine components in the flatpak haven't fully resolved the issue with running DOSBox for this particular game.

[error.log](https://github.com/user-attachments/files/19381973/error.log)

**Comment by GB609** [comment]
Thanks for the error log. You misunderstood me about the flatpak update. I meant that it still is broken and i have to prepare another pr for it. So, for further tests with the flatpak, we have to wait until this is complete.

**Comment by 4Vertikal4** [comment]
> Thanks for the error log. You misunderstood me about the flatpak update. I meant that it still is broken and i have to prepare another pr for it. So, for further tests with the flatpak, we have to wait until this is complete.

Thanks for clarifying! I
