### ISSUE TITLE
Update license of .deb

### ISSUE THREAD

**Issue by TheMatthew** [sharkwouter/minigalaxy#7]
The project appears to be GPL, the deb file states the project is proprietary. I think the problem is spacing on the copyright file.

ref: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#header-paragraph

**Comment by sharkwouter** [comment]
Thanks for bringing this to my attention. This will be resolved in the next release

**Comment by sharkwouter** [comment]
I've just released [version 0.9.1](https://github.com/sharkwouter/minigalaxy/releases/tag/0.9.1) in which this is resolved.

**Comment by TheMatthew** [comment]
![image](https://user-images.githubusercontent.com/2235031/71538145-41d79480-28f4-11ea-864f-8ee43b16fccb.png)
Sorry, looks like it's still an issue. :(

**Comment by sharkwouter** [comment]
Thanks for testing

**Comment by sharkwouter** [comment]
This seems to be an issue with Gnome Software. I've reported this issue and my research into the issue to the Gnome Software issue tracker. You can find it here: https://gitlab.gnome.org/GNOME/gnome-software/issues/875#note_674618

**Comment by sharkwouter** [comment]
I've added the "waiting for input" label to this issue, but in this case this is not targeted towards you. I'll update this issue if I get a reply on the Gnome Software issue tracker

**Comment by sharkwouter** [comment]
If this is not fixed now, it is a bug in Gnome Software and we can't really do anything with it.
